[PLAY-1978] Icons: pb_icon auto isn't a valid svg height/width (#5337)
**What does this PR do?** A clear and concise description with your
runway ticket url.

[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-1978)

Currently, Playbook Icons are returning the following errors:
```
Error: <svg> attribute height/width: Expected length, "auto".
``` 

This is occurring as we are setting a value of 'auto' on height/width
attributes on SVG tags, which require explicit values like '100',
'10px', '10%', etc.

This PR resolves that issue by replacing the adjusting width attribute
to '1em' (per our [Icon
scss](https://github.com/powerhome/playbook/blob/master/playbook/app/pb_kits/playbook/pb_icon/_icon.scss))
and removing height attribute from SVG tags.

**Note:** This issue only occurs on browsers like Chrome and Safari. The
error is not triggered in Firefox, etc.

**Screenshots:** Screenshots to visualize your addition/change
<img width="1358" height="795" alt="Screenshot 2025-10-13 at 12 38
57 PM"
src="https://github.com/user-attachments/assets/a01c597c-521f-4617-af65-f638ced79b2b"
/>


**How to test?** Steps to confirm the desired behavior:
1. Go to any page on Playbook and inspect. You should not see any
'Error: svg' in the console.


#### Checklist:
- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new
kit`, `deprecated`, or `breaking`. See [Changelog &
Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels)
for details.
- [ ] **DEPLOY** I have added the `milano` label to show I'm ready for a
review.
- [ ] **TESTS** I have added test coverage to my code.
- [ ] **SEMVER** I have added a `minor`, `major`, or `patch` label for
release.
- [ ] **RC** I have added an `inactive RC` label if not an active RC.