[CHMN-60] HaveIBeenPwned passphrase (#1462)
* Add passwordStrength variant to react and example skeleton

* Add some prelim examples

* Move password strength into separate file

* Example with popover on textinput

* Refactor last example

* Example with custom password strength function

* Add Owasp example as well

* Cleanup and comment

* Generate passphrase kit

* Add some basic strength calc to show the progress bar

* Start implementing hide/show functionality

* Move icon and toggle based on showing passphrase or not

* Move password logic into helper js file, show diagnostic info for now

* Conditionally render info icon based on tips prop

* Add popover with tips when icon is showing

* Style popover

* Add dark support

* Add min length support

* Memoize password strength calculator

* Cleanup/remove comments

* Add confirmation prop

* Remove hack for dark popover

* Add confirmation prop to hide meter and tips

* Address spacing feedback

* Add inputprops and pass to textinput

Allow name, id, etc to be set on inner text input

* Add default bottom margin

* Add dark link color for link

* Add callback for strength changing

* Fix dark spacing for progress and text

* Add common and responsive prop for tips

* Remove exploratory passphrase work in text input

* Add docs for passphrase kit

* Correct issue removing scss

* Add ruby kit for passphrase

Attempted to copy generator

* Don't show the progress bar when input is empty

Use visiblity: hidden to maintain the spacing. No jumping when starting to type

* Fix undefined reference to value.length

* Comment out spec to get reviewable kits online

* Add basic props to rails kit

* Update react kit to support uncontrolled element

* Remove unused owasp package

* Add common passphrase example

* Cleanup

Change password to passphrase where possible, clean up css, fix dark spacing issue

* Add other rails docs

* Remove onstrengthchange prop from rails kit

* Update passphrase spec

* Add jest tests for passphrase

* Small tweaks, spelling

* Missing comma in rails example

* Use hmtl label around element

* Move passphrase into form menu section

* Add an explanation for strength meter example

May make the inputs all indepentent depending on review, but this attempts to make it more clear why they were linked before

* Add passwordStrength variant to react and example skeleton

* Add some prelim examples

* Move password strength into separate file

* Example with popover on textinput

* Refactor last example

* Example with custom password strength function

* Add Owasp example as well

* Cleanup and comment

* Generate passphrase kit

* Add some basic strength calc to show the progress bar

* Start implementing hide/show functionality

* Move icon and toggle based on showing passphrase or not

* Move password logic into helper js file, show diagnostic info for now

* Conditionally render info icon based on tips prop

* Add popover with tips when icon is showing

* Style popover

* Add dark support

* Add min length support

* Memoize password strength calculator

* Cleanup/remove comments

* Add confirmation prop

* Remove hack for dark popover

* Add confirmation prop to hide meter and tips

* Address spacing feedback

* Add inputprops and pass to textinput

Allow name, id, etc to be set on inner text input

* Add default bottom margin

* Add dark link color for link

* Add callback for strength changing

* Fix dark spacing for progress and text

* Add common and responsive prop for tips

* Remove exploratory passphrase work in text input

* Add docs for passphrase kit

* Correct issue removing scss

* Add ruby kit for passphrase

Attempted to copy generator

* Don't show the progress bar when input is empty

Use visiblity: hidden to maintain the spacing. No jumping when starting to type

* Fix undefined reference to value.length

* Comment out spec to get reviewable kits online

* Add basic props to rails kit

* Update react kit to support uncontrolled element

* Remove unused owasp package

* Add common passphrase example

* Cleanup

Change password to passphrase where possible, clean up css, fix dark spacing issue

* Add other rails docs

* Remove onstrengthchange prop from rails kit

* Update passphrase spec

* Add jest tests for passphrase

* Small tweaks, spelling

* Missing comma in rails example

* Use hmtl label around element

* Move passphrase into form menu section

* Add an explanation for strength meter example

May make the inputs all indepentent depending on review, but this attempts to make it more clear why they were linked before

* Fix alpha order

* Reorder imports and remove comment

* SCSS feedback/touchup

* Add missing final newline

* Remove mistakenly duplicated packages in package.json

Bad merge conflict resolution. These were moved to dev dependencies

* Implement HIBP password check function

* Add prop for showing hibp passwords

* Add inline display to label

Nitro global css causing problems

* Implement useHaveIBeenPwned hook and build example

* Fix typo

* Expose strength as a data prop, include rails example for pwned

* Move passwordstrength into hook

* Fix return value in useEffect

* Fix merge issue

* Add spec for data attribute

* Add .md explaining hibp option

* Default to unpwnd if api ddoesnt respond

Also styling for one line if

* Correct dependencies array for useEffect

These won't change in a typical use case, but if for some reason they do, they should be respected

* Use descriptive variables for clarity

Co-authored-by: Jason Cypret <jason@jasoncypret.com>