[PLAY-2688] Global Props Automated Testing: Standardize with Shared Helpers (#5681)
**What does this PR do?**
- Standardize global props testing with helper files
(`global_props_test_helper.rb` and `globalPropsTestHelper.js`).
- Replace / DRY up classname and responsive testing in all current
tests.
  - Note: there are props that aren't as standardized:
    -  `hover`: is a nested hash/object instead of a string
    - `html_options` doesn't set a class, but instead attributes
- Add new testing
- Test on multiple kits (instead of just Body): Body, Button, Card,
Title, Text Input, Flex, Link, Badge
- Test that a global prop does NOT generate classnames when prop is nil
or not passed
- Test that a global prop handles invalid values gracefully without
throwing errors or generating unexpected classes
- Identified potential bugs. Commented and provided ways to skip this
testing.
- React global props can have errors if you pass `null` because `null`
is an object
    - `TypeError: Cannot convert undefined or null to object`. 
  - Invalid values will still generate CSS classes. 
    - e.g., `display="invalid"` -> generates "display_invalid" class
- When numeric values are passed to props that use `camelToSnakeCase`,
rendering fails with: `TypeError: word.split is not a function`
  - Flex global props are not compatible with certain kits
- Text Input doesn't support flex props (alignContent, alignItems,
alignSelf, justifyContent, justifySelf, flexDirection, flexWrap,
flexGrow, flexShrink)
- `React does not recognize the 'alignContent' prop on a DOM element`
- I don't ever see a case where we'd actually use flex global props with
text inputs, but the same can be said for a lot of the other global
props.
- Flex **kit** level props can lead to conflicts with global flex props.
- e.g., `align_self` in `flex.rb` only supports %w[start end center
stretch none], but in `align_self.rb` has two more %w[auto start end
center stretch baseline] (auto and baseline).

https://runway.powerhrg.com/backlog_items/PLAY-2688

**How to test?**
Testing should pass CI. 

#### Checklist:
- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new
kit`, `deprecated`, or `breaking`. See [Changelog &
Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels)
for details.
- [x] **DEPLOY** I have added the `milano` label to show I'm ready for a
review.
- [x] **TESTS** I have added test coverage to my code.
- [x] **SEMVER** I have added a `minor`, `major`, or `patch` label for
release.
- [x] **RC** I have added an `inactive RC` label if not an active RC.